---
version: "1.0"

services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        container_name: speedtest-tracker
        ports:
            - 8087:80
            - 9087:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:IbCN6M7QIZQyuLLb+BEhvpVPHzWv3hijhJsW0UIKR7c=
            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE=0 0,4,8,12,16,20 * * *
        volumes:
            - /home/docker01/speedtest/config:/config