version: "3"
services:
  wyl:
    image: aceberg/watchyourlan
    network_mode: "host"      
    restart: unless-stopped
    volumes:
    - ~/.dockerdata/wyl:/data/WatchYourLAN
    environment:
      TZ: Europe/Warsaw              
      IFACES: "ens19"